### PR TITLE
Demo adjustments

### PR DESCRIPTION
**Pull request by sberube**
Hi,

I fixed a couple of issues regarding the Ionic Cordova AppAuth demo. Feel free to comment 😁

This is related to issue #14 

Thanks!

### CODE REVIEW

**Comment by CarlosTorrecillas** [comment]
Nice one, pretty much to what I did to get that working and eventually managed to run it on the emulator with success. Not sure if that happened to you or not (in capacitor at least) but sometimes in the emulator the first attempt to go to IS somehow hangs. If you cancel the request and trigger it again it works. It’s a bit fleaky as it does not manifest all the time therefore I’m not sure whether that’s a bug in the code or not. IMO is not since the browser version works perfectly.

The only thing I still haven’t managed to do is rather than having a wrapper around http with the auth-http I wanted to have an interceptor to add the header but I get all the time infinite loops when I first attempt to log in

**Comment by sberube** [comment]
We use a regular Angular HTTP interceptor for our internal requests :

```
@Injectable()
export class TokenInterceptor implements HttpInterceptor {

  constructor(private authService: AuthService) { }

  intercept(
    req: HttpRequest<any>,
    next: HttpHandler
  ): Observable<HttpEvent<any>> {
     return from(this.handleAccess(req, next));
  }

  private async handleAccess(request: HttpRequest<any>, next: HttpHandler): Promise<HttpEvent<any>> {
    try {
      let changedRequest = request;
      const token = await this.authService.getValidToken();
      console.log(token);

      const headerSettings: { [name: string]: string | string[]; } = {};
      for (const key of request.headers.keys()) {
        headerSettings[key] = request.headers.getAll(key);
      }
      if (token) {
        headerSettings.Authorization = 'Bearer ' + token.accessToken;
      }
      headerSettings['Content-Type'] = 'application/json';
      const newHeader = new HttpHeaders(headerSettings);

      changedRequest = request.clone({
        headers: newHeader
      });
      return next.handle(changedRequest).toPromise();
    } catch (err) {
      console.error(err);
      return next.handle(request).toPromise();
    }
  }
}
```

This is not the most elegant code but it's work 🤷‍♂️. The ```AuthService``` provided by the ```ionic-appauth``` package expose the 
```getValidToken``` function. By using this function you ensure that the token you get is always valid.

```
this.authService.getValidToken();
````

And then we register this interceptor in our ```core.module``` like this.

```
@NgModule({
  imports: [CommonModule, HttpClientModule, IonicModule],
  providers: [
    {
      provide: StorageBackend,
      useFactory: storageFactory,
      deps: [Platform]
    },
    {
      provide: Requestor,
      useFactory: httpFactory,
      deps: [Platform, HttpClient]
    },
    {
      provide: Browser,
      useFactory : browserFactory,
      deps: [Platform]
    },
    {
      provide: HTTP_INTERCEPTORS,
      useClass: TokenInterceptor,
      multi: true,
    },
  ],
})
export class CoreModule extends EnsureImportedOnceModule {
  public constructor(@SkipSelf() @Optional() parent: CoreModule) {
    super(parent);
  }
}
```

**Comment by CarlosTorrecillas** [comment]
Thank you very much for sharing it. I missed the try-catch bit, everything else was in place! Thanks again 👍

**Comment by CarlosTorrecillas** [comment]
Hi @sberube ,

Really quick one, when you are in the emulator, how do you handle the redirect? I mean, I can see in identity server the incoming request being "http://localhost" (the Android emulator) however when I redirect back, the APP is not able to get "http://localhost" working and therefore I get a ERR_CONNECTION_REFUSED - not sure if you have come across that error.

**Pull request merged**
